# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0022_auto_20190614_1151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set([('user', 'course')]),
        ),
        migrations.AlterIndexTogether(
            name='courseenrollment',
            index_together=set([('user', 'created')]),
        ),
    ]
